name: Daily Python Scripts

on:
  schedule:
    - cron:  '0 10 * * *'
    - cron:  '0 16 * * *'
    - cron:  '0 20 * * *'


jobs:
  run-scripts:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run script1.py
      run: python script1.py

    - name: Run script2.py
      run: python script2.py
