name: Run Python Scripts

on: [push]  

jobs:
  run-scripts:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt  

    - name: Run hashtag_scraping.py
      run: python hashtag_scraping.py  

    - name: Run post_img.py
      run: python post_img.py  
